# -*- coding: utf-8 -*-
"""Exercícios_de_aula

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tBiUDvspuI3u-DqaQ1-xTdgsTkZV_mpn
"""

linguagem = {}

for dicionario in range(0, 2):
  print('\nEnquete de linguagem favorita')
  nome = input('\nQual o seu nome ?\t').title()
  lingua = input('\nQual a sua linguagem favorita ?\t').title()
  linguagem[nome] = lingua
  linguagem.copy()

for k, v in linguagem.items():
  print('\n' + str(k) + ' respondeu a enquete de linguagem favorita e sua linguagem favorita é ' + str(v))
  linguagem.copy()